In [1]:
import numpy as np

In [2]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [4]:
# 데이터 타입을 지정하여 구성
np.array([1,4,2,3], dtype=np.float)

/var/folders/jp/8vy66mjd2cdbdvtn4d3f5zjr0000gn/T/ipykernel_7288/4039598636.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,4,2,3], dtype=np.float)


array([1., 4., 2., 3.])

In [6]:
# list comprebension[루프]
np.array([range(i, i + 3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# 초기화 가능한 여러가지 함수 제공

# 1차원을 만드는 zeros
np.zeros(10)

# 1차원을 만들고 1로 채우는 ones
np.ones((3,5))

# 초기값을 임의로 설정해서 채우는 full
# 2행 3열에 5로 채워라
np.full((2,3),5)

# 배열을 생성하는 np.arange
# arange(start, end, step) end쪽이 -1로 빠짐

# 0부터 9까지 2로 증가하는 배열 생성하라
np.arange(0,10,2)

# 균등하게 interval을 구성할 수 있는 linspace
# 0부터 100까지 인터벌 5개 구성
np.linspace(0, 100, 5, dtype=int)


array([  0,  25,  50,  75, 100])

In [21]:
# 데이터 모의 구성 시 많이 사용하는 random 함수
# 3행 3열로 랜덤데이터 생성하라, 기본으로 데이터는 0-1 사이의 수 생성
np.random.random((3,3))

# 범위를 제공하는 randint
# 행 3열로 랜덤데이터 생성하라, 단 0-10까지의 수 10은 포함 X
np.random.randint(0,10,(3,3))

# 정규분포를 나타내는 normal
# normal(평균, 표준편차, (행, 열))
np.random.normal(0,1,(3,3))

array([[4, 4, 1],
       [2, 5, 6],
       [6, 8, 2]])