In [2]:
import numpy as np

In [2]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [3]:
# 데이터 타입을 지정하여 구성
np.array([1,4,2,3], dtype=np.float)

/var/folders/jp/8vy66mjd2cdbdvtn4d3f5zjr0000gn/T/ipykernel_16721/2733277739.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,4,2,3], dtype=np.float)


array([1., 4., 2., 3.])

In [4]:
# list comprebension[루프]
np.array([range(i, i + 3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 초기화 가능한 여러가지 함수 제공

# 1차원을 만드는 zeros
np.zeros(10)

# 1차원을 만들고 1로 채우는 ones
# 3행 5열에 1로 채워라
np.ones((3,5))

# 초기값을 임의로 설정해서 채우는 full
# 2행 3열에 5로 채워라
np.full((2,3),5)

# 배열을 생성하는 np.arange
# arange(start, end, step) end쪽이 -1로 빠짐

# 0부터 9까지 2로 증가하는 배열 생성하라
np.arange(0,10,2)

# 균등하게 interval을 구성할 수 있는 linspace
# 0부터 100까지 인터벌 5개 구성
np.linspace(0, 100, 5, dtype=int)


array([  0,  25,  50,  75, 100])

In [6]:
# 데이터 모의 구성 시 많이 사용하는 random 함수
# 3행 3열로 랜덤데이터 생성하라, 기본으로 데이터는 0-1 사이의 수 생성
np.random.random((3,3))

# 범위를 제공하는 randint
# 행 3열로 랜덤데이터 생성하라, 단 0-10까지의 수 10은 포함 X
np.random.randint(0,10,(3,3))

# 정규분포를 나타내는 normal
# normal(평균, 표준편차, (행, 열))
np.random.normal(0,1,(3,3))

array([[-0.30542476,  0.2531995 , -0.52148734],
       [-0.92574061,  0.22983979, -0.39608674],
       [ 0.53905333,  1.1038252 , -1.63754446]])

In [16]:
#230712
#seed 함수에 seed값을 주면 재현성 문제 해결
np.random.seed(0)

#integer를 random하게 만드는 randint
arr1 = np.random.randint(10, size=6) #0부터 10까지의 수 중 ...
arr2 = np.random.randint(10, size=(2,3))

#ndim(차원정보), shape(행/열, 원소의 구조 정보), size(원소의 개수), dtype(data type)를 나타냄
print("arr1:\n%s" % arr1)
print("ndim : %d, shape : %s, size: %d, dtype: %s\n" %
     (arr1.ndim, arr1.shape, arr1.size, arr1.dtype))
print("arr2:\n%s" % arr2)
print("ndim : %d, shape : %s, size: %d, dtype: %s\n" %
     (arr2.ndim, arr2.shape, arr2.size, arr2.dtype))

# arr1:
# [5 0 3 3 7 9]
# ndim : 1, shape : (6,), size: 6, dtype: int64

# arr2:
# [[3 5 2]
#  [4 7 6]]
# ndim : 2, shape : (2, 3), size: 6, dtype: int64

arr1:
[5 0 3 3 7 9]
ndim : 1, shape : (6,), size: 6, dtype: int64

arr2:
[[3 5 2]
 [4 7 6]]
ndim : 2, shape : (2, 3), size: 6, dtype: int64



In [24]:
#인덱싱 : 단일 원소에 접근하는 기법
arr1
#array([5, 0, 3, 3, 7, 9])
arr1[0], arr1[5], arr1[-6], arr1[-1]
# (5, 9, 5, 9)

arr2
# 2행 3열 2차원 shape의 arr2
# array([[3, 5, 2],
#        [4, 7, 6]])
# 단일 인덱싱을 사용해 첫 번째 원소에 접근
arr2[-1, -3], arr2[-1,-1]
# (4, 6)

# 인덱스를 이용해 새로운 값 지정 가능
arr2[0,0] = 9
arr2
# array([[9, 5, 2],
#        [4, 7, 6]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#슬라이싱
arr3 = np.arange(10)
arr3

#[start:end:step]
#end필수 start,step 제외 가능
arr3[0:5:1]

array([0, 1, 2, 3, 4])

In [31]:
#reshape 명령어 행/열 변환
arr2 = np.arange(12).reshape(-1,4)
#비어있는 슬라이싱 연산자 사용 시 전체집합을 부분집합으로 반환
arr2[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#230719
list1 = [1,2,3]
list2 = [4,5,6]

#list를 연결하는 concatenate
np.concatenate([list1, list2])

# axis라는 파라미터를 이용해서 방향을 지정한다.

arr1 = np.concatenate([list1, list2], axis=0)
arr1

arr2 = arr1.reshape(-1, 3)
arr2

# array([[1, 2, 3],
#        [4, 5, 6]])

np.concatenate([arr2, arr2], axis=0)

# array([[1, 2, 3],
#        [4, 5, 6],
#        [1, 2, 3],
#        [4, 5, 6]])

np.concatenate([arr2, arr2], axis=1)

# array([[1, 2, 3, 1, 2, 3],
#        [4, 5, 6, 4, 5, 6]])

# axis를 사용한 경우 축이 2개일 때 0과 1 두 개의 축이 생겨서 파라미터로 지정 가능하다.

# axis1과 같은 함수는 vstack(vertical stack)이고
# axis0과 같은 함수는 hstack(horizontal stack)이다.

np.vstack([arr2, arr2])
# array([[1, 2, 3],
#        [4, 5, 6],
#        [1, 2, 3],
#        [4, 5, 6]])
np.hstack([arr2, arr2])
# array([[1, 2, 3, 1, 2, 3],
#        [4, 5, 6, 4, 5, 6]])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# 행열 구조를 동일하게 맞춰주는 브로드캐스팅
